"""add_household_tables

Revision ID: 137017825f82
Revises: l2m3n4o5p6q7
Create Date: 2026-04-08 01:16:32.685957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '137017825f82'
down_revision: Union[str, Sequence[str], None] = 'l2m3n4o5p6q7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_households_id'), 'households', ['id'], unique=False)
    op.create_table('household_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('invitee_email', sa.String(length=320), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_household_invites_id'), 'household_invites', ['id'], unique=False)
    op.create_index(op.f('ix_household_invites_invitee_email'), 'household_invites', ['invitee_email'], unique=False)
    op.create_index(op.f('ix_household_invites_token_hash'), 'household_invites', ['token_hash'], unique=True)
    op.create_table('household_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'user_id', name='uq_household_member')
    )
    op.create_index(op.f('ix_household_memberships_id'), 'household_memberships', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_household_memberships_id'), table_name='household_memberships')
    op.drop_table('household_memberships')
    op.drop_index(op.f('ix_household_invites_token_hash'), table_name='household_invites')
    op.drop_index(op.f('ix_household_invites_invitee_email'), table_name='household_invites')
    op.drop_index(op.f('ix_household_invites_id'), table_name='household_invites')
    op.drop_table('household_invites')
    op.drop_index(op.f('ix_households_id'), table_name='households')
    op.drop_table('households')
    # ### end Alembic commands ###
