"""initial schema

Revision ID: a047a3ff3bf1
Revises: 
Create Date: 2026-04-06 12:42:00.816331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a047a3ff3bf1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_sent_at', sa.DateTime(), nullable=True),
    sa.Column('username_encrypted', sa.String(length=512), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('monthly_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month_encrypted', sa.String(length=512), nullable=False),
    sa.Column('salary_planned_encrypted', sa.String(length=512), nullable=True),
    sa.Column('salary_actual_encrypted', sa.String(length=512), nullable=True),
    sa.Column('total_planned_encrypted', sa.String(length=512), nullable=True),
    sa.Column('total_actual_encrypted', sa.String(length=512), nullable=True),
    sa.Column('remaining_planned_encrypted', sa.String(length=512), nullable=True),
    sa.Column('remaining_actual_encrypted', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_data_id'), 'monthly_data', ['id'], unique=False)
    op.create_table('monthly_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monthly_data_id', sa.Integer(), nullable=False),
    sa.Column('name_encrypted', sa.String(length=512), nullable=False),
    sa.Column('category_encrypted', sa.String(length=512), nullable=False),
    sa.Column('planned_amount_encrypted', sa.String(length=512), nullable=True),
    sa.Column('actual_amount_encrypted', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['monthly_data_id'], ['monthly_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_expenses_id'), 'monthly_expenses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monthly_expenses_id'), table_name='monthly_expenses')
    op.drop_table('monthly_expenses')
    op.drop_index(op.f('ix_monthly_data_id'), table_name='monthly_data')
    op.drop_table('monthly_data')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
